---
# Theming / Template Options
keyword_config: #These settings are global, use wisely
  SvrName: '$ServerName' # $ refers to edition config's children
  Dir1: '$DocumentRoot' # Use $$ to escape the $, don't edit these two
  ExampleTemplate : 'Changed Phrase' # Check template and edit to suit your needs
  PORTnum: '$PortNum'
  test: '$'
editor_config: # All must be strings so use the quotes
  ServerName: 'Example1.com' ######## You are looking for this
  DocumentRoot: 'D:\Example1' ######## And this
  HostsPath: 'C:\Windows\System32\drivers\etc\hosts'
  VhostsPath: 'C:\xampp\apache\conf\extra\httpd-vhosts.conf'
  PortNum: '80' ### Maybe this
template_path:
  HostsTemplatePath: '..\Config\'
...