---
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Theming / Template Options
keyword_config: #These settings are global to all templates, use wisely
  SvrName: '$ServerName' # $ refers to edition config's children
  Dir1: '$DocumentRoot' # Use $$ to escape the $, don't edit these two
  ExampleTemplate : 'Changed Phrase' # Check template and edit to suit your needs
  PortNumber1: '80'
  JustSoYouKnowThisFeautureExist100: '$ThisValuePointsTo'
editor_config: # All must be strings so use the quotes
  ServerName: 'Example1.com' ######## You are looking for this
  DocumentRoot: 'D:\Example1' ######## And this too, you can edit these
  HostsPath: 'C:\Windows\System32\drivers\etc\hosts'
  VhostsPath: 'C:\xampp\apache\conf\extra\httpd-vhosts.conf'
  EditIncludes: 'Both' # 'Hosts', 'Vhosts' or 'Both'
  SavesToOutput: 'True' #or 'False'
  OutputPath: '..\Output\' #Output is overwritten if same server name
  ThisValuePointsTo: "This, haha. Use wisely, $$ to escape the first $"
template_config:
  HostsTemplatePath: '..\Config\hosts_template.txt'
  VhostsTemplatePath: '..\Config\vhosts_template.txt'
  EditType : 'xampp localhost' #You can change this to any string you want to be matched, for just append use 'append'
  EditOption : '-' # You may change to '+' now. It is implemented
  #These two options are enabled. With great power comes great responsibilities
  #For append type, use '-' for bottom, '+' for top
  #For string type, use '-' to insert below, '+' for above
...